/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tydLXQOrIqm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function Main() {
  return (
    (<div
      className="flex flex-col items-center w-full min-h-screen bg-gradient-to-b from-pink-500 to-red-500 text-white">
      <header className="flex items-center justify-between w-full px-4 pt-8">
        <h1 className="text-lg font-semibold">Interval Timer</h1>
      </header>
      <main className="flex flex-col items-center justify-center flex-1 w-full">
        <div className="text-6xl font-bold">03:15</div>
        <button
          className="flex items-center justify-center w-16 h-16 mt-4 bg-white rounded-full">
          <PlayIcon className="w-8 h-8 text-red-500" />
        </button>
      </main>
      <div className="w-full p-4 bg-white rounded-t-3xl">
        <div className="space-y-2">
          <div className="flex items-center justify-between p-4 bg-green-100 rounded-md">
            <div className="flex items-center space-x-2">
              <PlayIcon className="w-6 h-6 text-green-500" />
              <span className="text-gray-700">Start</span>
            </div>
            <span className="text-green-500">00:05</span>
          </div>
          <div className="flex items-center justify-between p-4 bg-red-100 rounded-md">
            <div className="flex items-center space-x-2">
              <PauseIcon className="w-6 h-6 text-red-500" />
              <span className="text-gray-700">Rest</span>
            </div>
            <span className="text-red-500">00:05</span>
          </div>
          <div className="flex items-center justify-between p-4 bg-blue-100 rounded-md">
            <div className="flex items-center space-x-2">
              <RefreshCwIcon className="w-6 h-6 text-blue-500" />
              <span className="text-gray-700">Rounds</span>
            </div>
            <span className="text-blue-500">20X</span>
          </div>
        </div>
      </div>
    </div>)
  );
}

function PauseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect x="14" y="4" width="4" height="16" rx="1" />
      <rect x="6" y="4" width="4" height="16" rx="1" />
    </svg>)
  );
}


function PlayIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>)
  );
}


function RefreshCwIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M8 16H3v5" />
    </svg>)
  );
}
